### ISSUE TITLE
ctrl-. for hush by default?

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/atom-tidalcycles#102]
ctrl-. in SuperCollider silences the synths. I think there's already a shortcut in atom for hush, but it could be nice to make ctrl-. work for sending `hush` to tidal as well.

**Comment by ndr-brt** [comment]
I agree. Just one question, what's the mac os x shortcut? `ctrl-.` or `cmd-.`?

**Comment by ndr-brt** [comment]
it seems to be `cmd-.`:
https://doc.sccode.org/Reference/KeyboardShortcuts.html
