### ISSUE TITLE
Cannot Boot Atom - TidalCycles

### ISSUE THREAD

**Issue by jyfoster3** [tidalcycles/atom-tidalcycles#107]
Initially performed Windows Choco Install as seen in the powershell screenshot below.
GHC installation failed, but later performed and installed.
Reinstalled Atom TidalCycles package multiple times, with the same error to no avail.

Able to troubleshoot with:
https://tidalcycles.org/index.php/Troubleshooting_a_Tidal_install
and recreate expected output from import Sound.Tital.Context in GHCI. 

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [tidalcycles](https://github.com/tidalcycles/atom-tidalcycles) package 3.10.0

### Stack Trace

Uncaught Error: Cannot call write after a stream was destroyed

```
At events.js:171

Error [ERR_STREAM_DESTROYED] [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:411:19)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Socket.Writable.write (_stream_writable.js:299:11)
    at Ghci.writeLine (/packages/tidalcycles/lib/ghci.js:20:24)
    at REPL.tidalSendLine (/packages/tidalcycles/lib/repl.js:138:15)
    at REPL.tidalSendExpression (/packages/tidalcycles/lib/repl.js:129:10)
    at doIt (/packages/tidalcycles/lib/repl.js:177:12)
    at REPL.evalWithRepl (/packages/tidalcycles/lib/repl.js:181:5)
    at REPL._eval (/packages/tidalcycles/lib/repl.js:154:10)
    at HTMLElement.tidalcyclesEval (/packages/tidalcycles/lib/repl.js:39:38)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:349786)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:348261)
    at AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:1:765573)
    at EventEmitter.t (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:1:773496)
    at EventEmitter.emit (events.js:194:13)
```

### Commands

```
     -6:11.6.0 tidalcycles:boot (input.hidden-input)
     -5:34.5.0 core:paste (input.hidden-input)
     -5:25.8.0 tidalcycles:reboot (input.hidden-input)
     -5:13.5.0 core:backspace (input.hidden-input)
     -4:59.7.0 tidalcycles:reboot (input.hidden-input)
     -0:42.5.0 core:backspace (input.hidden-input)
     -0:34 tidalcycles:reboot (div.package-detail)
  2x -0:24.2.0 tidalcycles:eval (div.package-detail)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
gcc-make-run 0.2.12 
gpp-compiler 3.0.7 
tidalcycles 3.10.0 
w3c-validation 0.4.0 
```

**Comment by jyfoster3** [comment]
![2020-06-17 02_40_34-](https://user-images.githubusercontent.com/61032853/85183087-253b6a00-b250-11ea-8eff-5d7574b0da57.png)

**Comment by yaxu** [comment]
Hi, it looks like you ran out of disk space

**Comment by jyfoster3** [comment]
Oh - @yaxu I actually cleared disk space and have been able to fully install.

**Comment by jyfoster3** [comment]
Output from my CMD line just a second ago:
Microsoft Windows [Version 10.0.18362.900]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\jyosh>ghci
GHCi, version 8.10.1: https://www.haskell.org/ghc/  :? for help
Prelude> import Sound.Tidal.Context
Prelude Sound.Tidal.Context>

**Comment by jyfoster3** [comment]
This is the most recent output after trying to boot on Atom:

`
No configured ghc path
Ghci command: ghci
Ghc-pkg command: ghc-pkg
Load BootTidal.hs from C:\Users\jyosh\AppData\Roaming\cabal\x86_64-windows-ghc-8.10.1\tidal-1.4.3\BootTidal.hs
t>
t>
t>Listening for controls on 127.0.0.1:6010
t> 
Load BootTidal.hs from C:\Users\jyosh\AppData\Roaming\cabal\x86_64-windows-ghc-8.10.1\tidal-1.4.3\BootTidal.hs
t>
t>
t>Listening for controls on 127.0.0.1:6010
Control listen failed. Perhaps there's already another tidal instance listening on that port?
Tempo listener failed (is one already running?)
t>
Load BootTidal.hs from C:\Users\jyosh\AppData\Roaming\cabal\x86_64-windows-ghc-8.10.1\tidal-1.4.3\BootTidal.hs
t>Leaving GHCi.
t>
t>Listening for controls on 127.0.0.1:6010
Control listen failed. Perhaps there's already another tidal instance listening on that port?
Tempo listener failed (is one already running?)
t>`

**Comment by yaxu** [comment]
Looks like you're booting tidal multiple times

**Comment by jyfoster3** [comment]
Yes, but even after just booting once, the error message seems to show:
`
No configured ghc path
Ghci command: ghci
Ghc-pkg command: ghc-pkg
Load BootTidal.hs from C:\Users\jyosh\AppData\Roaming\cabal\x86_64-windows-ghc-8.10.1\tidal-1.4.3\BootTidal.hs
t>
t>
t>Listening for controls on 127.0.0.1:6010
`

I was able to hear audio and do the tutorial in SuperCollider, but yet to figure out what this ghc path issue means...

**Comment by yaxu** [comment]
That's not an error, it's just printed for information.
