### ISSUE TITLE
[error] can not working on mac 

### ISSUE THREAD

**Issue by Tokyodays** [tidalcycles/atom-tidalcycles#108]
hi.
i did update atom-tidalcyles
version is 10.13.6
but its not working.
its error has appearance in atom console.

```
t>/Users/****/Documents/Github/tidal-master/BootTidal.hs:16:29: error:
    • Couldn't match type ‘Bool’ with ‘Pattern ControlMap’
      Expected type: ControlPattern
        Actual type: Bool
    • In the second argument of ‘streamOnce’, namely ‘False’
      In the expression: streamOnce tidal False
      In an equation for ‘once’: once = streamOnce tidal False
   |
16 |     once = streamOnce tidal False
   |                             ^^^^^


    • Variable not in scope: d1 :: ControlPattern -> t
    • Perhaps you meant ‘dt’ (imported from Sound.Tidal.Context)
```

im already did this command in terminal.
brew install ghc
brew install cabal-install
cabal update
cabal install tidal --lib

what do i have to do for bugfix?
mac os version is 10.13.6

**Comment by ndr-brt** [comment]
what's your ghc's version? Could be this problem:
https://github.com/tidalcycles/atom-tidalcycles/issues/88
Try the suggested workaround.

**Comment by yaxu** [comment]
I think this is almost definitely due to ~/Documents/Github/tidal-master/BootTidal.hs being an old version. You might have customised it but it needs updating. The latest version is here: https://github.com/tidalcycles/Tidal/blob/main/BootTidal.hs

**Comment by Tokyodays** [comment]
@ndr-brt 
version is this
The Glorious Glasgow Haskell Compilation System, version 8.0.1

@yaxu 
should i replace that file?

**Comment by yaxu** [comment]
@Tokyodays yes, that should fix it. Please reopen if not.
