### ISSUE TITLE
import Scales and Chords

### ISSUE THREAD

**Issue by lvm** [tidalcycles/atom-tidalcycles#11]
TidalCycles 0.9 contains scales and chords which perphaps could to be added in the startup file by calling these two imports:
```haskell
import qualified Sound.Tidal.Scales as Scales
import qualified Sound.Tidal.Chords as Chords
```

**Comment by ndr-brt** [comment]
Does make sense mantain support to 0.x version?
This issue should be closed?

**Comment by yaxu** [comment]
Agreed
