### ISSUE TITLE
Uncaught TypeError: Cannot read property 'writeLine' of null

### ISSUE THREAD

**Issue by harryboneuk** [tidalcycles/atom-tidalcycles#114]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Mac OS X 10.13.6
**Thrown From**: [tidalcycles](https://github.com/tidalcycles/atom-tidalcycles) package 3.11.0

### Stack Trace

Uncaught TypeError: Cannot read property 'writeLine' of null

```
At /Users/hb/.atom/packages/tidalcycles/lib/repl.js:132

TypeError: Cannot read property 'writeLine' of null
    at REPL.tidalSendLine (/packages/tidalcycles/lib/repl.js:132:15)
    at REPL.tidalSendExpression (/packages/tidalcycles/lib/repl.js:123:10)
    at REPL.hush (/packages/tidalcycles/lib/repl.js:58:10)
    at HTMLElement.tidalcyclesHush (/packages/tidalcycles/lib/repl.js:43:38)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349963)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:348438)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:726014)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:733937)
    at EventEmitter.emit (events.js:200:13)
    at Object.onMessage (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/init.js:42:16)
```

### Commands

```
     -0:56.4.0 core:save (input.hidden-input)
     -0:34.6.0 tidalcycles:boot (input.hidden-input)
  2x -0:29.1.0 core:backspace (input.hidden-input)
     -0:28.4.0 core:move-right (input.hidden-input)
     -0:28.1.0 editor:newline (input.hidden-input)
     -0:15.6.0 tidalcycles:eval (input.hidden-input)
     -0:12.3.0 tidalcycles:hush (input.hidden-input)
     -0:01.4.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
tidalcycles 3.11.0 
```

**Comment by ndr-brt** [comment]
what's the output of the tidalcycles console?

**Comment by harryboneuk** [comment]
Sure I'll put what I can see. 

Configuration in Atom is:

"*":
  core:
    projectHome: "/User/hb/.ghcup/bin"
    telemetryConsent: "limited"
    themes: [
      "atom-dark-ui"
      "one-dark-syntax"
    ]
  "exception-reporting":
    userId: "3b965466-3089-4033-be99-e2606cf9e48d"
  tidalcycles:
    bootTidalPath: "ghc-pkg"
    ghciPath: "/User/hb/.ghcup/bin"
  welcome:
    showOnStartup: false

On SuperCollider it says 

Number of Devices: 3
   0 : "Built-in Microph"
   1 : "Built-in Output"
   2 : "Scarlett 2i2 USB"

"Built-in Microph" Input Device
   Streams: 1
      0  channels 2

"Built-in Output" Output Device
   Streams: 1
      0  channels 2

Thank you!

**Comment by ndr-brt** [comment]
Tidalcycles console is the panel in the bottom of atom that shows up when you evaluate the first tidalcycles expression.

But, looking at your configuration, you have to remove "ghc-pkg" from the "bootTidalPath" entry.
Here are the instructions for that entry:
https://github.com/tidalcycles/atom-tidalcycles#boot-tidal-path
(If you don't have your custom BootTidal file, you should leave it empty)

**Comment by ndr-brt** [comment]
@harryboneuk did you resolve? can the issue be closed?

**Comment by harryboneuk** [comment]
Hi @ndr-brt still can't find a solution. Have deleted everything and did the Tidal-Bootstrap again but the Atom console still doesn't open. Feel free to close it because I'm not sure what my other options are

**Comment by ndr-brt** [comment]
Did you remove the `bootTidalPath` row from the configuration? Do you see any other error message?

**Comment by harryboneuk** [comment]
I can't as the console isn't accessible nor can I delete it from the terminal.

Are you able to do a screenshot (or something) just to reiterate this point and show specifically removing the bootTidalPath row again, incase I'm not looking in the right place.

**Comment by harryboneuk** [comment]
<img width="743" alt="Screen Shot 2020-11-01 at 17 17 18" src="https://user-images.githubusercontent.com/72912246/97809731-aecf5f80-1c66-11eb-8a2a-0aa02e1740b3.png">
Having said that - i ran the ghci in terminal and this is a new error message that showed

**Comment by harryboneuk** [comment]
also this 
<img width="575" alt="Screen Shot 2020-11-01 at 17 35 12" src="https://user-images.githubusercontent.com/72912246/97809996-a2e49d00-1c68-11eb-8f87-417754ce6fca.png">

**Comment by ndr-brt** [comment]
that's not a problem with atom-tidalcycles plugin...
better to continue discussion on https://club.tidalcycles.org/t/atom-not-opening-on-mac-10-13-6/2300/11
