### ISSUE TITLE
Atom won't boot TidalCycles

### ISSUE THREAD

**Issue by ghost** [tidalcycles/atom-tidalcycles#127]
Hey all, 

I've tried for hours to get Atom to boot TidalCycles but I keep getting this error below: 

https://pastebin.com/sehCTUBw

cabal install tidal command in Powershell worked fine for me so I'm really confused!

**Comment by yaxu** [comment]
Hi @seventhlamb, what version of the tidalcycles package do you have installed in atom? Have you tried upgrading it to the latest?

**Comment by seventhlamb** [comment]
Hey @yaxu !

I've actually resolved my issue, apologies for wasting your time!

Many thanks :)

**Comment by yaxu** [comment]
Good news !
