### ISSUE TITLE
No or empty console

### ISSUE THREAD

**Issue by mbutz** [tidalcycles/atom-tidalcycles#131]
Hi,

when I try to use Tidal with Atom I don't get a console within Atom. I also do get an error (as you can see in the screenshot) but I can use Atom as it seems without problems.

![atom-tidal-error](https://user-images.githubusercontent.com/3934249/101499544-aeb13680-396d-11eb-9e55-cf8c3ec38c2d.png)

The critical issue is the missing console and therefore no visible error messages.

I am on

* Linux Mint 19.3
* SuperDirt 1.1.3
* Tidal 1.6.1

**Comment by ndr-brt** [comment]
the error in the right is telling me that you have an old ghc version that can't interpret the `prompt-cont` line contained in the `BootTidal.hs` file, there's a troubleshooting section about that in `README.md` file
https://github.com/tidalcycles/atom-tidalcycles#some-flags-have-not-been-recognized-prompt-cont

**Comment by mbutz** [comment]
Hi,

yes, that's true, right now I am running on 8.0.2. But checking the installed packages I see the following installed:

* ghc (version 8.0.2)
* ghc-8.6.4 (as it says: 8.6.4) - so I have it but it does not seem to be used

Now I thought I just get rid of the package `ghc` but then synaptic tells me it will also remove `cabal-install` which came with the Tidal installation (following the [userbase article about installation](https://tidalcycles.org/index.php/Linux_installation)).

So now I am confused. I assume, if I do not have `cabal-install` I will not be able to update Tidal if necessary. So this somehow seems to be a cat chasing its tail. Can you point me again into the right direction?

I fully understand if you say this is not the place to give installation advisory. Let me know and I will ask this question at the Tidal Club.

**Comment by ndr-brt** [comment]
Yes, if it's not about this plugin, that's not the right place to ask ;)
