### ISSUE TITLE
Mute/unmute audible patterns

### ISSUE THREAD

**Issue by gadfly16** [tidalcycles/atom-tidalcycles#134]
It would by very useful to be able to mute/unmute `d1`, `d2`, etc. with a keyboard shorcut like `Ctrl+1`, `Ctrl+2`, etc.

If possible it could be done for all the channels at once as well. For that I suggest `Ctrl+Shift+.` . It seems available in my editor.

**Comment by ndr-brt** [comment]
I just opened a pr with the implementation, the only issue I had is that the `ctrl+shift+.` shortcut didn't work, maybe is already used in my system, will release it in the next days.
