### ISSUE TITLE
syntax highlight not working for d10 / d11 / d12

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/atom-tidalcycles#154]
A small thing but threw someone a bit in a workshop .. d10 + doesn't get coloured in the atom plugin the same way as d1-d9.

**Comment by ndr-brt** [comment]
I tried but on my installation neither `d1`, `d2`, ... get coloured.
But could be a nice feature to colour them

**Comment by yaxu** [comment]
Ah interesting.. The workshop participant was on a mac, and I'm on Linux and see the same behaviour 

![image](https://user-images.githubusercontent.com/27940/119827203-c87d1080-bef0-11eb-8645-3e082d1c3967.png)
