### ISSUE TITLE
integrating tidal-listener

### ISSUE THREAD

**Issue by onthepeakofnormal** [tidalcycles/atom-tidalcycles#157]
Hey!
I've been working on distributing the tidal-listener so it works on machines that don't have ghc installed. You can check it out here:
https://github.com/onthepeakofnormal/tidal-listener/actions
I think it would be nice to be able to replace ghci by it, I'm not really familiar with javascript so I can't do it myself, but I'd be happy to extend the tidal-listener side, which currently doesn't have a lot of features.

I also noticed, that currently the ghc-pkg binary needs to be on the $PATH. 
Why exactly is this needed?

**Comment by yaxu** [comment]
@onthepeakofnormal I think ghc-pkg might be used to find the `data` folder and therefore BootTidal.hs . As I think tidal-listener would take care of such initialisation then it wouldn't be needed on the editor side.

**Comment by yaxu** [comment]
@shawnlawson was looking at tidal-listener integration with the https://github.com/shawnlawson/jensaarai atom plugin

**Comment by ndr-brt** [comment]
Interesting, I didn't know the existence of that plugin.

At the moment we could introduce tidal-listener as a togglable feature in the plugin. I read on discord that's only working on Windows right?

**Comment by onthepeakofnormal** [comment]
It's working on windows and linux.
There is no github action to compile and package it for linux though, but I'm currently working on that and should get it done soon.
After that I might look into mac

**Comment by ndr-brt** [comment]
Cool, because I'm a linux user and I would need that to implement the features.
Will be available on the "packages" section of the tidal-listener repository?

**Comment by yaxu** [comment]
Yes I think we're all linux users here, somehow working to make life easy for windows + mac people! 

`cabal install` should do it.

What @onthepeakofnormal has done is compile a tidal-listener that ships only with the libraries it needs, and doesn't need ghc installed. So a huge leap forward for end-users, but devs can just compile their own.

**Comment by ndr-brt** [comment]
I took a look at the tidal-listener wiki, whoa, that would bring a lot of interesting features.
Maybe we can start with the "eval code" basic feature, adding "tidal-listener" as a interpreter and make the plugin sending an osc message on code evaluation and printing result to the console instead of starting ghci and sending code to it.

**Comment by shawnlawson** [comment]
I think my Jensaarai package is still loading up Tidal as a stdin/stdout process. Although, in there I do have connections for sending OSC to/from TouchDesigner, which could be reused. Additionally, in a private repo I have an OSC to/from tidal-listener Atom package. I can ask the other author about opening that up for looking at/copying/whatever.

**Comment by ndr-brt** [comment]
Thanks, I already implemented the logic to communicate with tidal-listener, the problem that I'm not able to make tidal-listener work :smile: 
https://github.com/tidalcycles/tidal-listener/issues/12

**Comment by ndr-brt** [comment]
Ok, now it's starting, but at every line of code evaluated I get this error:
```
Compile error: : error:
    Could not find module Sound.Tidal.Context
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
```

also if I evaluate `import Sound.Tidal.Context`

**Comment by ndr-brt** [comment]
Ok, now it's working, I have some questions:
* the pattern should be sent without the `d1`/`d2` etc?
* how can functions like `hush`, `setcps` etc... be defined?
* why generic haskell syntax like `let` `do` etc... do not work?

**Comment by ndr-brt** [comment]
Ok, released this so it can be tested. As I wrote in the previous comment, there are some differences with tidal-in-ghci

**Comment by yaxu** [comment]
> Ok, now it's working

Great! Ok now things get interesting..

>     * the pattern should be sent without the `d1`/`d2` etc?

Yes. We could also make a command that simulates ghci-like behaviour, but I guess the intention with the API is that the editor gets a bit smarter about the code structure, rather than 'just' being an interface for sending blocks of text to haskell. For example the feedforward editor automatically assigns numbers to patterns, putting a VU meter next to each one, with visual cues telling you whether the pattern is muted or not, and flashing mininotation elements as corresponding sounds are triggered.

>     * how can functions like `hush`, `setcps` etc... be defined?

The draft API is here:
  https://github.com/tidalcycles/tidal-listener/wiki

I can't remember offhand whether cps is implemented.. But we should make the cps API two-way, so the cps can be shown in the client.

>     * why generic haskell syntax like `let` `do` etc... do not work?

It's not an IO context. I'm not sure if we can support on-the-fly definitions via [hint](https://hackage.haskell.org/package/hint).

**Comment by ndr-brt** [comment]
Ok, super, so this will take a little more to be implemented.

> > ```
> > * why generic haskell syntax like `let` `do` etc... do not work?
> > ```
> 
> Basically because it's not a ghci wrapper. I'm not sure if we can support on-the-fly definitions via [hint](https://hackage.haskell.org/package/hint).

For me this is a game-changer, the possiblity to define custom functions, the possibility to use functions like `all`, transiction functions like `xfadeIn`, `clutchIn`, etc...
I remember that we implemented that in feedforward, that is capable to load a script file with some functions defined:
https://github.com/yaxu/feedforward/blob/eacc665acc231fbd11b34bbaabae76cadeee22f0/src/TidalHint.hs#L69

Would be nice to implement that possibility into `tidal-listener` too.

**Comment by yaxu** [comment]
`all` and transitions would be additional api calls yep.

I see hint has a `runStmt` call which can bind new names.

**Comment by ndr-brt** [comment]
After #163 and #164 I think tidal-listener is pretty integrated into the plugin.
Still miss some features like `hush` and `setcps` but I think that's better to open specific issue for those.
