### ISSUE TITLE
Code highlighting

### ISSUE THREAD

**Issue by hellocatfood** [tidalcycles/atom-tidalcycles#160]
Is it possible to get code highlighting like what is seen in FeedForward https://github.com/yaxu/feedforward that is, the code/samples are highlighted when they are played (see gif below for example). 

![Peek 2021-07-03 22-14](https://user-images.githubusercontent.com/151947/124367128-81e7a800-dc4c-11eb-9c06-a123618d07d8.gif)

**Comment by ndr-brt** [comment]
For sure one of the first feature to be implemented with the integration of `tidal-listener`.
There's some work to do before though.
More info: https://github.com/tidalcycles/atom-tidalcycles/issues/157

**Comment by ndr-brt** [comment]
Now it's in a usable state:  #164 
Unfortunately it works only for a single pattern evalueted on the first line.
Other improvements will be made after the resolution of this:
https://github.com/tidalcycles/tidal-listener/issues/15

**Comment by yaxu** [comment]
Nice one! will have a look at the api later
