### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by ghostinthemud** [tidalcycles/atom-tidalcycles#173]
Hello. New here, so not 100% sure if this is where this goes.
I have already searched for the issue but what I found hasn't been helpful.
I am on Windows 10 / Atom.
So from what I understand, Tidal Cycles is not installed properly.
I just don't know how to do that.
The install tutorial page isn't super helpful.
I did the automatic install and I'm still getting all sorts of errors.
So I uninstalled, looked at the install guide, and tried to do manual installation.
Chocolatey and Haskell appear to have installed properly.
When I tried to install Tidal Cycles with the command given in the guide,
PowerShell (admin mode) tells me it failed to build a few things which are required by Tidal.
"blaze-builder" and "indexed-traversable" failed.
Tidal Cycles will not boot in Atom, and thus all commands give the error "variable not in scope."

I have no idea what I did wrong.
Any help would be appreciated. Thanks.

**Comment by yaxu** [comment]
Welcome @ghostinthemud , sorry to hear these problems.

You can find fellow travellers in the installation section of the tidal club forum:
  https://club.tidalcycles.org/c/installation/5

If you don't find the same problem/solution there, feel free to make a post. Please include copy and paste of full error messages you get, so we can find the clues.
