### ISSUE TITLE
multiline eval at end of buffer causes Atom to hang

### ISSUE THREAD

**Issue by kindohm** [tidalcycles/atom-tidalcycles#19]
I think the latest PR that we merged from @fand has caused a bug. If a multi-line block that is at the very end of a file, Atom hangs when the block is eval'd. If I revert the PR, the problem does not happen. If I add the PR code back, Atom will hang. I will try to add more specific bug details later. A number of people have notified us of crashes/hangs within the past day. I may revert the PR so that users do not have problems until we can resolve this properly.

**Comment by kindohm** [comment]
fixed in 9abcee6aae728762455a47db8398052ea7339391

**Comment by fand** [comment]
I'm sorry for the bug... thanks! 😿
