### ISSUE TITLE
Limit key commands to your own grammar

### ISSUE THREAD

**Issue by crucialfelix** [tidalcycles/atom-tidalcycles#2]
We merged this once:

https://github.com/tidalcycles/atom-tidalcycles/pull/1

But it's been reverted.

Please limit this to your own grammar. You are calling your function even if somebody is trying to use atom-supercollider.  Atom is a bit confusing with the key commands, so package developers really need to cooperate on this. Please don't pollute the global key command spec.

Thanks,

**Comment by yaxu** [comment]
I'm confused as I can't see any commits since your patch was merged:
  https://github.com/tidalcycles/atom-tidalcycles/commits/master

**Comment by kindohm** [comment]
@crucialfelix your change was not reverted in the source code here on github, but the package was not published to the Atom package repository after the change (there is no "prepare release" commit). 

I recently installed the atom-tidalcycles package, and I see that the package code on my local machine does not match what is on github. Perhaps we just need to publish the package. Or...  maybe I'm misunderstanding something.

I'm going to test the latest code with this PR, just to make sure it works for me, and if it does I'll prepare and publish a new relesae.

**Comment by kindohm** [comment]
The PR doesn't appear to work in my environment. None of the keybindings work for me. I'll dig in and see if I can understand why.

**Comment by crucialfelix** [comment]
Oh I see, you just never released it.

Git pull
Apm publish patch

Thanks, hannes at udk was having this issue.

**Comment by kindohm** [comment]
Looks like the keymap also uses an incorrect value for the grammar name. I'll do another PR to resolve _that_ issue, and then we'll publish. 

Thanks @crucialfelix for helping find all this.

**Comment by crucialfelix** [comment]
Thanks guys. See if it should be = and not ~=

I think I did it wrong.

**Comment by kindohm** [comment]
Got it working, and published a new version to APM.
