### ISSUE TITLE
When using stack ghc, how should command line arguments be handled?

### ISSUE THREAD

**Issue by jarmitage** [tidalcycles/atom-tidalcycles#23]
Issue
- Currently, if you use `stack ghc` as your `ghci path` in settings, the interpreter will fail to parse strings correctly leading to errors and no patterns being sent by `tidal` to `SuperDirt`
- This is because the command line arguments required when launching `ghc` are being sent to `stack` instead of `ghc`:
https://github.com/tidalcycles/atom-tidalcycles/blob/1af570666720b86c4a4bb8ee76fc71f4d5b29673/lib/repl.js#L49
- When using `stack`, the command line argument should be `stack ghc -- --interactive -XOverloadedStrings`. This ensures the `XOverloadedStrings` goes to `ghc` and not `stack`

Options
- Option A: specify in the `readme` or elsewhere that users should paste `stack ghc -- --interactive -XOverloadedStrings` when using `stack`
- Option B: the plugin should handle this and users should only be required to type `stack ghc`. Would this create extra maintenance pain?
- Option C: ???

See also: http://lurk.org/groups/tidal/messages/topic/7znL4SI9uwsUGfuwq51cys/

**Comment by yaxu** [comment]
Thanks for this,
I think changing the package to not send a commandline option, and then piping `:set -XOverloadedStrings` with the rest of the initialisation is the way forward.. So I vote option b

(I think you mean `stack ghc -- --interactive -XOverloadedStrings` rather than ghci)

**Comment by jarmitage** [comment]
This can be closed now: https://github.com/tidalcycles/atom-tidalcycles/commit/f35c5a30aba861acc0c1308b1e2e2ba85b0f1f8d

**Comment by bgold-cosmos** [comment]
For some reason the fix doesn't always seem to work, it is sometimes necessary to use `stack exec ghci --` as the GHCi command in the atom-tidalcycles preferences.

**Comment by ndr-brt** [comment]
it's still an issue?

**Comment by ndr-brt** [comment]
closed due to inactivity
