### ISSUE TITLE
Indentation issues when loading custom BootTidal.hs

### ISSUE THREAD

**Issue by ericfairbanks** [tidalcycles/atom-tidalcycles#29]
If it put this _(as far as I can tell)_ perfectly valid bit of Haskell in my BootTidal.hs, GHCI complains about indentation or mismatched bracket issues. I've tried re-arranging my functions in a variety of ways, but the only things it seems to accept are one-liners.

```haskell
describeLetter :: Char -> String
describeLetter c =
    if c >= 'a' && c <= 'z'
        then "Lower case"
        else if c >= 'A' && c <= 'Z'
            then "Upper case"
            else "Not an ASCII letter"
```

**Comment by digitalohm** [comment]
same problem here in trying to put the following into boot.tidal :(

let startclock d p = do
                  now <- getNow
                  d $ (pure (nextSam now)) ~> p

oneshot d p = startclock d $ seqP [(0, 1, p)]

**Comment by ndr-brt** [comment]
> If it put this _(as far as I can tell)_ perfectly valid bit of Haskell in my BootTidal.hs, GHCI complains about indentation or mismatched bracket issues. I've tried re-arranging my functions in a variety of ways, but the only things it seems to accept are one-liners.
> 
> ```haskell
> describeLetter :: Char -> String
> describeLetter c =
>     if c >= 'a' && c <= 'z'
>         then "Lower case"
>         else if c >= 'A' && c <= 'Z'
>             then "Upper case"
>             else "Not an ASCII letter"
> ```

You should wrap multiline code like this:
```
:{
describeLetter :: Char -> String
describeLetter c =
    if c >= 'a' && c <= 'z'
        then "Lower case"
        else if c >= 'A' && c <= 'Z'
            then "Upper case"
            else "Not an ASCII letter"
:}
```
And it will work correctly
