### ISSUE TITLE
High Sierra cause Tidal to not Work

### ISSUE THREAD

**Issue by mtfirn** [tidalcycles/atom-tidalcycles#30]
I have been using Tidal for about a year with no problems.  I updated to High Sierra and it fell apart.   I did a clean install of everything and when I went to reinstall Tidal using stack install tidal nothing happened.  When I use cabal install tidal it installs but when I try to run everything I get the following error

Warning: No local targets specified, so ghci will not use any options from your package.yaml / *.cabal files. Potential ways to resolve this: * If you want to use the package.yaml / *.cabal package in the current directory, use stack init to create a new stack.yaml. * Add to the 'packages' field of /Users/00953884/.stack/global-project/stack.yaml Configuring GHCi with the following packages: 
GHCi, version 8.2.2: http://www.haskell.org/ghc/ :? for help
Loaded GHCi configuration from /private/var/folders/qd/8ydvmnls6dn79znfnk85dgm4xn3sqf/T/ghci35642/ghci-script
Prelude> Prelude> can't load .so/.DLL for: /Users/00953884/.stack/snapshots/x86_64-osx/lts-10.3/8.2.2/lib/x86_64-osx-ghc-8.2.2/libHSzlib-0.6.1.2-7k8ElOnaocwBudwnpy07vK-ghc8.2.2.dylib (dlopen(/Users/00953884/.stack/snapshots/x86_64-osx/lts-10.3/8.2.2/lib/x86_64-osx-ghc-8.2.2/libHSzlib-0.6.1.2-7k8ElOnaocwBudwnpy07vK-ghc8.2.2.dylib, 5): Symbol not found: _deflateEnd
Referenced from: /Users/00953884/.stack/snapshots/x86_64-osx/lts-10.3/8.2.2/lib/x86_64-osx-ghc-8.2.2/libHSzlib-0.6.1.2-7k8ElOnaocwBudwnpy07vK-ghc8.2.2.dylib Expected in: flat namespace in /Users/00953884/.stack/snapshots/x86_64-osx/lts-10.3/8.2.2/lib/x86_64-osx-ghc-8.2.2/libHSzlib-0.6.1.2-7k8ElOnaocwBudwnpy07vK-ghc8.2.2.dylib)

Trying to create a stack.yaml with stack init just hangs the computer and doesn't actually do anything.  Does anyone have a solution for this?

**Comment by yaxu** [comment]
Are you using atom? If so, check in preferences > tidalcycles > settings > ghci path. If you've installed tidal using cabal, this should be set to just `ghci`. (if you're using stack, it should be set to `stack ghci`).

**Comment by mtfirn** [comment]
Yes, I am using atom.  I have tried both stack ghci and ghci which shows up in the preferences as Deafult:ghci . still get an error

**Comment by mtfirn** [comment]
I figured it out.  Apparently Apple came out with a Command Line Tools update that did not install or ask to be installed when xcode was run in High Sierra.  Once updated through terminal everything worked.
