### ISSUE TITLE
Indenting produces error

### ISSUE THREAD

**Issue by songproducer** [tidalcycles/atom-tidalcycles#33]
Tried to follow the tutorial here:
https://www.youtube.com/watch?v=XqOMbY0E31I&list=PLKgxw7RG3hcRHyBFsPr5opr1iu8wbNIgP&index=8

but get 
error: parse error on input ‘d1’

**Comment by ndr-brt** [comment]
Can you report the code?
Did you resolved?

**Comment by songproducer** [comment]
No, I’m Not sure which code to report. Also won’t have access to computer for about a week.

**Comment by yaxu** [comment]
I think it's just a matter of getting the indentation right. Haskell can be a bit picky.

I'll close this for now, but if there is particular code that causes this error please share it and we can have a look.
