### ISSUE TITLE
Change tidalRepl references to this.tidalRepl

### ISSUE THREAD

**Issue by diegodorado** [tidalcycles/atom-tidalcycles#35]
in `tidalcycles.js` I see `tidalRepl` is exported, but never set since it is not called with `this`
Although everything works, it would be useful to me to get access to these variable from another plugin where I am to wrap `tidalSendLine` function to preprocess the code to be sent.

I have tried this locally and works properly. I have changed these `tidalcycles.js` lines.

```javascript
    activate(state) {
        this.consoleView = new ConsoleView(state.consoleViewState);
        this.tidalRepl = new Repl(this.consoleView);
    },

    deactivate() {
        this.consoleView.destroy();
        this.tidalRepl.destroy();
    },

    serialize() {
        return {
            consoleViewState: this.consoleView.serialize()
        };
    }
```

**Comment by yaxu** [comment]
Hi! Just catching up with old things. If this is still current, could you please send it as a pull request?

**Comment by diegodorado** [comment]
I will!
