### ISSUE TITLE
high Sierra causes tidal cycles not to work

### ISSUE THREAD

**Issue by tomasraposo** [tidalcycles/atom-tidalcycles#36]

**Comment by tomasraposo** [comment]
hi there, 
so, im relatively new to live coding. I've installed all the required software to run tidal cycles via atom and supercollider but I don't seem to be able to get it running properly... the following message keeps appearing in atom after inserting a code line: 

I've also attached a print screen of the tidal bootstrap command line, which after running the dependencies says that tidal cabal package could not be installed, but im quite sure I've already done it...

<img width="567" alt="captura de ecra 2018-09-28 as 16 18 23" src="https://user-images.githubusercontent.com/43519486/46217532-24ef9280-c33a-11e8-972e-1516d5874811.png">

<img width="844" alt="captura de ecra 2018-09-28 as 16 17 54" src="https://user-images.githubusercontent.com/43519486/46217509-15704980-c33a-11e8-95cf-2282bde623cd.png">

thank you for your help.

**Comment by robjac** [comment]
I am also seeing this bug -- although i've previously used tidalcycles on high sierra. not sure what changed to have caused this.

the vscode plugin still works, so i can use that in the meantime.

**Comment by yaxu** [comment]
@tomasraposo It looks like a problem with installing tidalcycles, rather than something atom specific.
Try running `cabal update; cabal install tidal` from a commandline.
If that doesn't work, I'd recommend re-installing the haskell platform (the 'full' version) and trying again. https://www.haskell.org/platform/

**Comment by yaxu** [comment]
I've just noticed this post is very old, sorry for the delay. For a much faster response, join us on the #tidal-install channel on http://talk.lurk.org

**Comment by tomasraposo** [comment]
Hi Alex,

Thank you for replying, but I managed to sort it out. I just installed the
full version of haskell instead of the core one. It now works just fine.
Thank you so much for you reply!

cheers!

Alex McLean <notifications@github.com> escreveu no dia sexta, 23/11/2018
à(s) 06:38:
