### ISSUE TITLE
Errors on boot after update to 3.0.0

### ISSUE THREAD

**Issue by kgorlovsky** [tidalcycles/atom-tidalcycles#46]
After updating to 3.0.0 I'm constantly getting the bunch of errors on TidalCycles boot up in Atom. As a consequence, transitions like xfade etc. don't work.
Here is the list of errors:

    * Couldn't match type `Pattern ControlMap' with `Bool'
      Expected type: Pattern Double -> Bool
        Actual type: Pattern Double -> ControlPattern
    * In the second argument of `(.)', namely `cps'
      In the expression: asap . cps
      In an equation for `setcps': setcps = asap . cps

    * Couldn't match expected type `Time
                                    -> [ControlPattern] -> ControlPattern'
                  with actual type `Bool'
    * In the second argument of `transition', namely `True'
      In the expression: transition tidal True (xfadeIn 4) i
      In an equation for `xfade':
          xfade i = transition tidal True (xfadeIn 4) i

    * Couldn't match expected type `Time
                                    -> [ControlPattern] -> ControlPattern'
                  with actual type `Bool'
    * In the second argument of `transition', namely `True'
      In the expression: transition tidal True (xfadeIn t) i
      In an equation for `xfadeIn':
          xfadeIn i t = transition tidal True (xfadeIn t) i

    * Couldn't match expected type `Time
                                    -> [ControlPattern] -> ControlPattern'
                  with actual type `Bool'
    * In the second argument of `transition', namely `True'
      In the expression: transition tidal True (histpan t) i
      In an equation for `histpan':
          histpan i t = transition tidal True (histpan t) i

    * Couldn't match expected type `Time
                                    -> [ControlPattern] -> ControlPattern'
                  with actual type `Bool'
    * In the second argument of `transition', namely `True'
      In the expression: transition tidal True (wait t) i
      In an equation for `wait':
          wait i t = transition tidal True (wait t) i

    * Couldn't match expected type `Time
                                    -> [ControlPattern] -> ControlPattern'
                  with actual type `Bool'
    * In the second argument of `transition', namely `True'
      In the expression: transition tidal True (waitT f t) i
      In an equation for `waitT':
          waitT i f t = transition tidal True (waitT f t) i

    * Couldn't match expected type `Time
                                    -> [ControlPattern] -> ControlPattern'
                  with actual type `Bool'
    * In the second argument of `transition', namely `True'
      In the expression: transition tidal True (jump) i
      In an equation for `jump': jump i = transition tidal True (jump) i

    * Couldn't match expected type `Time
                                    -> [ControlPattern] -> ControlPattern'
                  with actual type `Bool'
    * In the second argument of `transition', namely `True'
      In the expression: transition tidal True (jumpIn t) i
      In an equation for `jumpIn':
          jumpIn i t = transition tidal True (jumpIn t) i

    * Couldn't match expected type `Time
                                    -> [ControlPattern] -> ControlPattern'
                  with actual type `Bool'
    * In the second argument of `transition', namely `True'
      In the expression: transition tidal True (jumpIn' t) i
      In an equation for jumpIn':
          jumpIn' i t = transition tidal True (jumpIn' t) i

    * Couldn't match expected type `Time
                                    -> [ControlPattern] -> ControlPattern'
                  with actual type `Bool'
    * In the second argument of `transition', namely `True'
      In the expression: transition tidal True (jumpMod t) i
      In an equation for `jumpMod':
          jumpMod i t = transition tidal True (jumpMod t) i

    * Couldn't match expected type `Time
                                    -> [ControlPattern] -> ControlPattern'
                  with actual type `Bool'
    * In the second argument of `transition', namely `True'
      In the expression:
        transition tidal True (mortal lifespan release) i
      In an equation for `mortal':
          mortal i lifespan release
            = transition tidal True (mortal lifespan release) i

    * Couldn't match expected type `Time
                                    -> [ControlPattern] -> ControlPattern'
                  with actual type `Bool'
    * In the second argument of `transition', namely `True'
      In the expression: transition tidal True (interpolate) i
      In an equation for `interpolate':
          interpolate i = transition tidal True (interpolate) i

    * Couldn't match expected type `Time
                                    -> [ControlPattern] -> ControlPattern'
                  with actual type `Bool'
    * In the second argument of `transition', namely `True'
      In the expression: transition tidal True (interpolateIn t) i
      In an equation for `interpolateIn':
          interpolateIn i t = transition tidal True (interpolateIn t) i

    * Couldn't match expected type `Time
                                    -> [ControlPattern] -> ControlPattern'
                  with actual type `Bool'
    * In the second argument of `transition', namely `True'
      In the expression: transition tidal True (clutch) i
      In an equation for `clutch':
          clutch i = transition tidal True (clutch) i

    * Couldn't match expected type `Time
                                    -> [ControlPattern] -> ControlPattern'
                  with actual type `Bool'
    * In the second argument of `transition', namely `True'
      In the expression: transition tidal True (clutchIn t) i
      In an equation for `clutchIn':
          clutchIn i t = transition tidal True (clutchIn t) i

    * Couldn't match expected type `Time
                                    -> [ControlPattern] -> ControlPattern'
                  with actual type `Bool'
    * In the second argument of `transition', namely `True'
      In the expression: transition tidal True (anticipate) i
      In an equation for `anticipate':
          anticipate i = transition tidal True (anticipate) i

    * Couldn't match expected type `Time
                                    -> [ControlPattern] -> ControlPattern'
                  with actual type `Bool'
    * In the second argument of `transition', namely `True'
      In the expression: transition tidal True (anticipateIn t) i
      In an equation for `anticipateIn':
          anticipateIn i t = transition tidal True (anticipateIn t) i

    Not in scope: `Sound.Tidal.Transition.mortalOverlay'
    No module named `Sound.Tidal.Transition' is imported.

**Comment by yaxu** [comment]
Hi, please update tidal itself with the following commands in a terminal window:
```
cabal update
cabal install tidal
```

**Comment by kgorlovsky** [comment]
yaxu, thanks for your help - now everything works!

**Comment by eerieear** [comment]
Worked for me too ! Thanks @yaxu !

**Comment by heliponto4** [comment]
hi there, i am now having the same problem. I tried to install the tidal library update as above, but I am getting this error message on my terminal:

"Warning: You asked to install executables, but there are no executables in
target: tidal. Perhaps you want to use --lib to install libraries instead."

Can someone help? Thanks!

**Comment by yaxu** [comment]
Hi @heliponto4, try
```
cabal install tidal --lib
```
