### ISSUE TITLE
BootTidal.hs load sequence is wrong

### ISSUE THREAD

**Issue by ndr-brt** [tidalcycles/atom-tidalcycles#58]
`README.md` is a little confusing about that, in the [Configurable boot options](https://github.com/tidalcycles/atom-tidalcycles#configurable-boot-options) chapter.

Before, it reports that by the plugin will choose a `default Tidal bootup sequence`, but can be defined `a path to your own custom boot`. At the end is possible to check an option to load the file in the current directory.

In the same chapter there's a list that shows the same 3 options but in inverted order.

Lookin into the code, it seems that the `useBootFileInCurrentDirectory` flag is not used, the default choice is that will be choosed the boot file in the current directory, then a custom file and, at the end, the default package boot file.

I propose to remove the `useBootFileInCurrentDirectory` and use this sequence:
1. if provided, the custom boot file path
2. boot file in the current directory
3. if no boot file exists in the current directory, choose the default package file.

**Comment by yaxu** [comment]
A suggestion for step 3:

Rather than shipping a BootTidal.hs of its own, the emacs plugin finds the path to the BootTidal.hs that comes with tidal itself: https://github.com/tidalcycles/Tidal/blob/master/tidal.el#L60

**Comment by ndr-brt** [comment]
that will be better! I will try to implement it soon, in the meantime I opened a basic PR.

**Comment by ndr-brt** [comment]
I opened another issue for the default tidal BootTidal.hs
