### ISSUE TITLE
Default BootTidal.hs path

### ISSUE THREAD

**Issue by ndr-brt** [tidalcycles/atom-tidalcycles#60]
Rather than shipping a BootTidal.hs of its own, the emacs plugin finds the path to the BootTidal.hs that comes with tidal itself: https://github.com/tidalcycles/Tidal/blob/master/tidal.el#L60

I think this is a good idea as it means that the default boot will always work. Currently if you upgrade the plugin but not the library (or vice-versa), you'll get confusing errors.

_Originally posted by @yaxu in https://github.com/tidalcycles/atom-tidalcycles/issues/58#issuecomment-544370946_

**Comment by kindohm** [comment]
@ndr-brt @yaxu do you envision that the Atom package would do an HTTP request to download `tidal.el` just before Tidal starts up? I am looking into implementing this same change in the VSCode extension but I think it would be good if we discussed the approach together.

**Comment by yaxu** [comment]
@kindohm it shouldn't need to, because BootTidal.hs is shipped with Tidal. It's not straightforward to find it, but @lennart and @ethancrawford now seem to have the emacs plugin finding it cross platform.

For linux and macos, the command to find it is `ghc-pkg describe $(ghc-pkg latest tidal) | grep data-dir | cut -f2 -d' '`

For windows, it's `echo off && for /f %a in ('ghc-pkg latest tidal') do (for /f \"tokens=2\" %i in ('ghc-pkg describe %a ^| findstr data-dir') do (echo %i))`

Implemented here: https://github.com/tidalcycles/Tidal/blob/master/tidal.el#L60

**Comment by kindohm** [comment]
ahhh yes of course. so it'll just read it from the Tidal package on the file system

**Comment by yaxu** [comment]
That's right. it does depend upon `ghc-pkg` being in the path, and the right one being first in the path.. It _might_ be worth taking the currently set path to `ghci`, and swapping ghci for ghc-pkg, to hopefully run the right one..

**Comment by ndr-brt** [comment]
Released v.3.5.2 with this feature.

**Comment by yaxu** [comment]
This doesn't seem to work under windows. I guess this is the case with the emacs plugin as well.

If I run `echo off && for /f %a in ('ghc-pkg latest tidal') do (for /f \"tokens=2\" %i in ('ghc-pkg describe %a ^| findstr data-dir') do (echo %i))` in a cmd shell, I get this:
```
\"tokens=2\" was unexpected at this time.
```
The shell then hangs and I have to close the window.

I haven't used DOS in a couple of decades, but trying to debug this below, maybe it's useful..

```
Microsoft Windows [Version 10.0.16299.192]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\alex>ghc-pkg latest tidal
tidal-1.4.3

C:\Users\alex>ghc-pkg describe tidal-1.4.3
name:                 tidal
version:              1.4.3
visibility:           public
id:                   tidal-1.4.3-HmYjdMbIgO9JRI53Npr0zB
key:                  tidal-1.4.3-HmYjdMbIgO9JRI53Npr0zB
license:              GPL-3.0-only
copyright:            (c) Tidal contributors, 2019
maintainer:
    Alex McLean <alex@slab.org>, Mike Hodnick <mike.hodnick@gmail.com>

author:               Alex McLean
stability:            Experimental
homepage:             http://tidalcycles.org/
synopsis:             Pattern language for improvised music
description:
    Tidal is a domain specific language for live coding pattern.

category:             Sound
abi:                  b8fdeadad01785490abde375d8ab3bc4
exposed:              True
exposed-modules:
    Sound.Tidal.Bjorklund Sound.Tidal.Carabiner Sound.Tidal.Chords
    Sound.Tidal.Config Sound.Tidal.Context Sound.Tidal.Control
    Sound.Tidal.Core Sound.Tidal.EspGrid Sound.Tidal.Params
    Sound.Tidal.ParseBP Sound.Tidal.Pattern Sound.Tidal.Scales
    Sound.Tidal.Simple Sound.Tidal.Stream Sound.Tidal.Tempo
    Sound.Tidal.Transition Sound.Tidal.UI Sound.Tidal.Utils
    Sound.Tidal.Version

import-dirs:
    C:\Users\alex\AppData\Roaming\cabal\x86_64-windows-ghc-8.8.1\tidal-1.4.3-HmYjdMbIgO9JRI53Npr0zB

library-dirs:
    C:\Users\alex\AppData\Roaming\cabal\x86_64-windows-ghc-8.8.1\tidal-1.4.3-HmYjdMbIgO9JRI53Npr0zB
    C:\tools\msys64\mingw64\lib

dynamic-library-dirs:
    C:\Users\alex\AppData\Roaming\cabal\x86_64-windows-ghc-8.8.1
    C:\tools\msys64\mingw64\lib

data-dir:
    C:\Users\alex\AppData\Roaming\cabal\x86_64-windows-ghc-8.8.1\tidal-1.4.3

hs-libraries:         HStidal-1.4.3-HmYjdMbIgO9JRI53Npr0zB
include-dirs:         C:\tools\msys64\mingw64\include
depends:
    base-4.13.0.0 bifunctors-5.5.5-4ytLOlflEzLFOIyeXkWecB
    bytestring-0.10.9.0 clock-0.8-BDr0ZJKaVWEAskyGHHBCXi
    colour-2.3.5-HwkwGdq0zHOAgUmo2lVa4V containers-0.6.2.1
    deepseq-1.4.4.0 hosc-0.17-C18VbpqYPEf7aj1mF46vqR
    mwc-random-0.14.0.0-1w5shRARrEll25HluX7Nq
    network-3.1.1.0-2vvFk8A20MJRifOkznfwm parsec-3.1.14.0
    primitive-0.7.0.0-BJKNB1CdxR09IS7Mq0RtDA text-1.2.4.0
    transformers-0.5.6.2 vector-0.12.0.3-3rAYgdX4S5EJIxiT2bfL32

haddock-interfaces:
    C:\Users\alex\AppData\Roaming\cabal\doc\x86_64-windows-ghc-8.8.1\tidal-1.4.3\html\tidal.haddock

haddock-html:
    C:\Users\alex\AppData\Roaming\cabal\doc\x86_64-windows-ghc-8.8.1\tidal-1.4.3\html
pkgroot: "C:\\Users\\alex\\AppData\\Roaming\\ghc\\x86_64-mingw32-8.8.1"

C:\Users\alex>ghc-pkg describe tidal-1.4.3 | findstr data-dir
data-dir:

C:\Users\alex>ghc-pkg describe tidal-1.4.3 ^| findstr data-dir
ghc-pkg: command-line syntax error
For usage information see 'ghc-pkg --help'.

C:\Users\alex>
```

**Comment by ethancrawford** [comment]
That's a shame... I swore I had a successful test on Windows 10 myself with the emacs plugin. Apologies 😕

**Comment by ethancrawford** [comment]
re the last command line syntax error in the above output, the `^` is only needed when it is embedded in the `for` construct from what I remember.

**Comment by ethancrawford** [comment]
will investigate this again shortly.

**Comment by yaxu** [comment]
Perhaps my path is long enough that it gets automatically wrapped onto the next line, so that the parsing doesn't work.
This might not have the wrapping behaviour: `ghc-pkg field tidal-1.4.4 data-dir`

**Comment by yaxu** [comment]
Yes this works for me under windows 10: `for /f "tokens=2" %i in ('ghc-pkg field tidal data-dir') do (echo %i)`

I also changed `\"tokens=2\"` for `"tokens=2"`, the double quotes were obviously escaped for quoting in the emacs plugin..

It might be better to do the parsing in the plugin though. For example I'm not sure if this would cope if there was a space in the path.

**Comment by ethancrawford** [comment]
The `\"tokens=2\" was unexpected at this time.` is definitely because of the escaped quotes (only needed in the emacs plugin). I'm attempting to see if I can install tidal in such a way that it ends up at a path with a space in it, to see how the script would handle it.

**Comment by ndr-brt** [comment]
uhm...ok, I have a PR ready for this... let's look at that all together :)
we could use for every OS the command:
`ghc-pkg field tidal data-dir`
then parsing will be handled by plugin, right?

I already implemented a fallback, in case of non-existent path resulting from this command, the plugin BootTidal.hs will be choosed

**Comment by ethancrawford** [comment]
Sounds like an excellent idea to me 👍

**Comment by ndr-brt** [comment]
this should be the working function:
```
tidalDataDir() {
    let dataDir = child_process
      .execSync(`ghc-pkg field tidal data-dir`)
      .toString().trim()

    return dataDir.substring(dataDir.indexOf(' ') + 1)
  }
```

unit tested, it works :)

**Comment by ethancrawford** [comment]
with and without spaces in the path?

**Comment by ndr-brt** [comment]
yep, with substring it takes the first occurrence of space in line, all the other spaces will be included in the path.

**Comment by yaxu** [comment]
Great, the only issue I see is if there are multiple copies of haskell installed. This can happen quite easily if someone has problems while installing tidal.. #68 could be a quick fix?

**Comment by ndr-brt** [comment]
ok, but that's another issue right? with PR #71 should be ok.

**Comment by yaxu** [comment]
I don't think it's a completely separate issue.
Currently everything should work for everyone, as long as tidal and the atom plugin are both up to date.
On its own PR https://github.com/tidalcycles/atom-tidalcycles/pull/71 might well break things for a lot of people if they have more than one version of Haskell installed.
I think best to fix #68 before the next release

**Comment by ndr-brt** [comment]
ok, I'm already on it ;)

**Comment by yaxu** [comment]
Super :)
