### ISSUE TITLE
Autoscroll in console not working

### ISSUE THREAD

**Issue by KonVas** [tidalcycles/atom-tidalcycles#65]
Not sure this is autoscroll, or something else. But new messages don't pop up in the console, instead I have to do it manually to see the last message.

**Comment by ndr-brt** [comment]
Your OS is mac os x?

**Comment by ndr-brt** [comment]
try version 3.5.1

**Comment by ndr-brt** [comment]
Got some other feedbacks from chat.toplap.org, it should be fixed
