### ISSUE TITLE
Use of ghci/ghc path

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/atom-tidalcycles#68]
Currently there's a setting for 'ghci path', with a value defaulting just to `ghci`
I think we really want a setting for the install location of ghc, then we can also use it for running `ghc-pkg`

So I suggest
1. Making this blank by default
2. Before using the path, stripping `ghci` from the end of it, if it exists
3. Using this path for running both `ghci` and `ghc-pkg`

**Comment by ndr-brt** [comment]
ok, just to see if I understand...
the "ghci" path is actually read from configuration, but "ghc-pkg" is not, so we could define a different behaviour for ghci path and obtain ghc-pkg path from that.

**Comment by ndr-brt** [comment]
maybe would be better to "deprecate" the actual ghci setting and define a new configuration setting to haskell `bin` folder, it would be cleaner

**Comment by yaxu** [comment]
Yes maybe. We only need one setting though.
Perhaps we just rename it to `Haskell (ghci) path`, so that people following old instructions will still know what to set.

Actually when I first saw it I assumed "Ghci path" meant path to ghci not including the filename. So I think it would be good to support both if possible with a little logic to strip ghci from the end of the path so either works

**Comment by ndr-brt** [comment]
Ok, committed the first version, now there's a function called `Ghci.commandPath(name)` that gives the command path based on `ghciPath` property value.

Tested, should handle all the cases.

Yeah, maybe we can rename the property, but doing that, people who set that property will lose the setting? Maybe we can just change the label and keep the `ghciPath` property name, just for backward compatibility... dunno if there's a way to change a property name without pain.

**Comment by yaxu** [comment]
Yes agreed, best to just change the label if anything.
At some point though it might be justified to rationalise everything with a 'major release', grouping together several breaking changes into one painful upgrade :)

**Comment by ndr-brt** [comment]
Released in 3.7.0
