### ISSUE TITLE
check for ghcup?

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/atom-tidalcycles#81]
Sorry to bring up the ghc path again, but the default install method for mac os and linux is via ghcup (https://www.haskell.org/ghcup/). ghci then ends up in `~/.ghcup/bin/ghci` 
However, often the user's PATH doesn't get properly updated, so running `ghci` doesn't find it. I wonder if the plugin could add a check for `~/.ghcup/bin/ghci` if a path isn't otherwise set?

**Comment by ndr-brt** [comment]
@yaxu in the same path (`~/.ghcup/bin`) there's also `ghc-pkg` command?
sorry but I installed it without ghcup

**Comment by ndr-brt** [comment]
oh, it does not matter, it will work anyway :)

**Comment by ndr-brt** [comment]
Released on 3.8.2

**Comment by yaxu** [comment]
@ndr-brt yes `~/.ghcup/bin/ghc-pkg` exists. Thanks!
