### ISSUE TITLE
Error loading boot tidal file since v.3.8.3

### ISSUE THREAD

**Issue by ndr-brt** [tidalcycles/atom-tidalcycles#88]
Seems a problem with GHC version 8.0.2:

console output:
```
$ ghci
GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help
Prelude> :script /.../tidal_boot_147.hs
Some flags have not been recognized: prompt-cont, 
d1 $ s "bd"

<interactive>:2:1: error: Variable not in scope: d1 :: t0 -> t

<interactive>:2:6: error: Variable not in scope: s :: [Char] -> t0
```

maybe we need a property to choose how to load the boot file?

**Comment by ndr-brt** [comment]
seems similar to:
https://github.com/tidalcycles/Tidal/issues/480

**Comment by ndr-brt** [comment]
one quick-and-dirt solution is to comment the `prompt-cont" line in BootTidal.hs:
https://forum.toplap.org/t/broken-tidal-after-update/783/7

**Comment by ndr-brt** [comment]
another, is to move the `prompt-cont` line at the end of file

**Comment by aziks** [comment]
this solution didn't work for me :(

**Comment by ndr-brt** [comment]
@aziks the error is the same?

**Comment by ndr-brt** [comment]
Problem explained into README file: #113
