### ISSUE TITLE
Escaping spaces

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/atom-tidalcycles#90]
This PR:
   https://github.com/tidalcycles/atom-tidalcycles/commit/127b208d9e542af538961a1740079c81b5e302de
... stops `~` in e.g. `~/.ghcup/bin/` from being expanded.

I suggest reverting it, and instead escaping spaces individually. In Unix (mac + linux) this is with `\`, e.g. `/Users/spider\ man/ghcup/bin/`. Under windows it seems to be with `^`, e.g. `cC\Users\spider^ man\ghcup\bin/`.

**Comment by ndr-brt** [comment]
In alternative in POSIX systems we can use backtick ````` and in windows keep the double quotes.
Each solution requires that the OS should be checked...

**Comment by ndr-brt** [comment]
Or, another solution, maybe simpler...
Replace the eventual starting `~` character with the result of `os.homedir()`

**Comment by ndr-brt** [comment]
fixed, resolving `~` before path evaluation: https://github.com/tidalcycles/atom-tidalcycles/pull/91
