### ISSUE TITLE
"/bin/sh: ghci: comand not found"

### ISSUE THREAD

**Issue by grossato** [tidalcycles/atom-tidalcycles#92]
hi,
I installed SuperCollider and haskell successful, but when I open the package in atom it cannot find ghci.
I tried to modify the path with the one I obtain using which, but the problem persist.
Do you have any idea on what to do?

thank you in advance.

**Comment by yaxu** [comment]
Hi @grossato , what o/s (windows/mac/linux) are you using?

**Comment by grossato** [comment]
sorry, you're right.
I'm using linux mint 19 (cinnamon)

**Comment by yaxu** [comment]
Ok how did you install haskell?

**Comment by grossato** [comment]
I used the command "sudo apt-get install build-essential cabal-install git jackd2". _ don't_ remember if I already had it installed for some reasons.

**Comment by yaxu** [comment]
Did you manage to solve this @grossato?

**Comment by grossato** [comment]
yes, sorry i didn't update this thread. The problem, apparantly, was something in Atom. I just re-installed it and everything worked. 
Thanks for helping!

**Comment by yaxu** [comment]
Great!
