### ISSUE TITLE
Cannot load tidal within atom plugin

### ISSUE THREAD

**Issue by diegodorado** [tidalcycles/atom-tidalcycles#93]
I can load tidal from commandline if I enter `ghci` and then load the boottidal.hs with `:script`
But it seem to be broken inside atom... what could be the cause of this?

This is what I see if I try to evaluate a line inside atom

```
Custom ghci path configured: ghci
Ghci command: ghci
Ghc-pkg command: ghc-pkg
Load BootTidal.hs from /home/diegodorado/.atom/packages/tidalcycles/lib/BootTidal.hs
GHCi, version 8.6.5: http://www.haskell.org/ghc/  :? for help

: error:
    Could not find module `Sound.Tidal.Context'
    It is not a module in the current program, or in any known package.
```

**Comment by diegodorado** [comment]
I can confirm that tidal is also working from tidalvim

**Comment by diegodorado** [comment]
Downgrading to version 3.1.0 of the plugin does work

**Comment by ndr-brt** [comment]
@diegodorado the file `/home/diegodorado/.atom/packages/tidalcycles/lib/BootTidal.hs` exists?

**Comment by diegodorado** [comment]
Yes it does.

**Comment by ndr-brt** [comment]
@diegodorado is the problem still present?

**Comment by diegodorado** [comment]
Mmm not sure really.... it is been a while i moved to tidalvim ...
reinstalled my system and dont currently have atom anymore...
