### ISSUE TITLE
I just UPDATED atom-tidalcycles 3.8.7

### ISSUE THREAD

**Issue by aziks** [tidalcycles/atom-tidalcycles#94]
SuperCollider and SuperDirt are running correctly and I checked ‘Sound.Tidal.Context’ and is installed, got this error in Atom:

: error:
    Could not find module ‘Sound.Tidal.Context’
    It is not a module in the current program, or in any known package.

 Variable not in scope: d1 :: t0 -> t

    • Variable not in scope: sound :: [Char] -> t0
    • Perhaps you meant ‘round’ (imported from Prelude)

**Comment by diegodorado** [comment]
had a similar problem... downgrade through apm does work.
I am sure there is an easy fix for this.... meanwhile you can uninstall the package, and install a previous version from apm

`apm install tidalcycles@3.1.0` worked for me

**Comment by aziks** [comment]
Ey thanks for the reply! I tried to downgrade to 3.1.0 but i got the same error:

Could not find module ‘Sound.Tidal.Context’

![image](https://user-images.githubusercontent.com/17042624/75099401-86647100-55c1-11ea-9357-d3c74836ef3e.png)

The thing is I can load this module in the console...

**Comment by aziks** [comment]
It's normal to have two BootTidal.hs ??

![image](https://user-images.githubusercontent.com/17042624/75099469-55d10700-55c2-11ea-80bb-a67e6574b0bb.png)

**Comment by yaxu** [comment]
Yes that's fine
Probably what's happening is that you have two versions of ghci installed and atom is guessing the wrong one. 
You can set the path to ghci explicitly in atom settings for the TidalCycles package

**Comment by yaxu** [comment]
@aziks Did you manage to sort this out ok?
