### ISSUE TITLE
Can't load BootTidal.hs if the path contains a space

### ISSUE THREAD

**Issue by ndr-brt** [tidalcycles/atom-tidalcycles#95]
As notified here: https://github.com/tidalcycles/atom-tidalcycles/issues/82#issuecomment-571222009

Also reported here: https://github.com/tidalcycles/Tidal/issues/561

**Comment by yaxu** [comment]
Looks like a ghci bug, reported upstream: https://gitlab.haskell.org/ghc/ghc/issues/18027

**Comment by yaxu** [comment]
There's a fix coming in ghc version 8.12

**Comment by ndr-brt** [comment]
Problem's solution explained into README file: #113
