### ISSUE TITLE
Customizing output text in post window

### ISSUE THREAD

**Issue by Git-Christopher** [tidalcycles/atom-tidalcycles#98]
greetings! i would like to propose adding a new feature to the atom-tidalcycles package. 

the feature would allow you to customize the text that appears in your post window upon a successful (error-free) eval.

the current output text defaults to "t>" but a user-customized text string could allow for a more conversational application in a live setting.

thank you for considering this feature!

**Comment by ndr-brt** [comment]
like a static string settable in configuration? i propose to mantain the `>` at the end, and let just the string before to be customizable

**Comment by Git-Christopher** [comment]
exactly. in [Kindohm's recent Eulerroom performance](https://www.youtube.com/watch?v=SZwhETSFiDw), it looks like he was able to customize his VSCode output.

**Comment by kindohm** [comment]
@Git-Christopher yes, the VSCode extension has some settings to post additional content to the output window - mainly for entertainment purposes :)  

In addition to the normal ghci output of `tidal>`, the extension will optionally append the following based on your configuration:

1. A count of the number of code evals performed
2. A string prefix before the eval count
3. A random message from a configured array of strings, controlled by a probability ranging from 0 to 1 on how likely a random message will be displayed.

These may or may not be useful to the Atom extension, but I thought I'd elaborate here since the performance with VSCode was referenced.

**Comment by Git-Christopher** [comment]
@kindohm thanks for the elaboration Mike! yes, it was quite entertaining :) 

in my mind, i'm imagining a "99 bottles of beer" countdown to give people a good chuckle. 

this is by no means a crucial feature ;)

**Comment by ndr-brt** [comment]
Ok, opened a simple pull request.
With this will be possibile to specify a custom message before `>`. `t` will be the default.
The `tidalcycles.filterPromptFromLogMessages` property will be removed because if it is `true` is impossible to customize the prompt.

**Comment by ndr-brt** [comment]
Add a eval count counter usable with the placeholder `%ec` in console prompt configuration.
What do you think? Other ideas?

**Comment by ndr-brt** [comment]
Added also a timestamp placeholder

**Comment by Git-Christopher** [comment]
maybe some sort of log of characters and/or events that were added/removed?

for example:

original code = `d1 $ s "bd*16"`

revised code = `d1 $ struct "t*16?" $ s "bd"`

output = 12 characters added, 8 events removed

**Comment by ndr-brt** [comment]
nice idea!
the character one is pretty simple, every eval we can count character number and keep the difference since the last evaluation.
the one with the events can't be done, because at the moment there's only a one-way communication between plugin and tidal.

**Comment by Git-Christopher** [comment]
ok cool! (yes, i thought the events might be impossible...)

**Comment by ndr-brt** [comment]
added the %diff placeholder, it prints the difference of length of the last two evaluations

**Comment by ndr-brt** [comment]
could be interesting let the user define some javascript code. e.g.
with a console prompt: *this is a random number:  `Math.random()`*
the output will be: *this is a random number: `0.5526626094958087`*

the ``` separator is an example, we could find another one (maybe three backticks?)

**Comment by ndr-brt** [comment]
The first version with placeholders is released in 3.10.0
